# Generated by Django 4.1.1 on 2022-09-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblBenchmark',
            fields=[
                ('bnc_id', models.AutoField(primary_key=True, serialize=False)),
                ('bnc_process', models.CharField(db_collation='utf8mb3_general_ci', max_length=255, unique=True)),
                ('bnc_normal', models.IntegerField(blank=True, null=True)),
                ('bnc_warning', models.IntegerField(blank=True, null=True)),
                ('bnc_critical', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_benchmark',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblClients',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(db_collation='utf8mb3_general_ci', max_length=255)),
                ('client_email', models.CharField(db_collation='utf8mb3_general_ci', max_length=200)),
                ('client_contact', models.CharField(db_collation='utf8mb3_general_ci', max_length=30)),
                ('client_address', models.TextField()),
                ('client_creation_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_clients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_id', models.IntegerField()),
                ('site_id', models.IntegerField()),
                ('system_id', models.IntegerField()),
                ('bnc_id', models.IntegerField()),
                ('event_value', models.IntegerField()),
                ('event_type', models.CharField(db_collation='utf8mb3_general_ci', max_length=15)),
                ('event_email', models.TextField(db_collation='utf8mb3_general_ci')),
                ('event_emaildelivery', models.IntegerField()),
                ('event_creation_date', models.DateTimeField(blank=True, null=True)),
                ('tmp_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblEventTmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(db_collation='utf8mb3_general_ci', max_length=255)),
                ('site', models.CharField(db_collation='utf8mb3_general_ci', max_length=255)),
                ('system', models.CharField(db_collation='utf8mb3_general_ci', max_length=255)),
                ('bench', models.CharField(db_collation='utf8mb3_general_ci', max_length=255)),
                ('event_value', models.IntegerField()),
                ('event_email', models.TextField(db_collation='utf8mb3_general_ci')),
                ('event_emaildelivery', models.CharField(db_collation='utf8mb3_general_ci', max_length=50)),
            ],
            options={
                'db_table': 'tbl_event_tmp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblSites',
            fields=[
                ('site_id', models.AutoField(primary_key=True, serialize=False)),
                ('site_name', models.CharField(db_collation='utf8mb3_general_ci', max_length=255)),
                ('site_email', models.CharField(db_collation='utf8mb3_general_ci', max_length=200)),
                ('site_contact', models.CharField(db_collation='utf8mb3_general_ci', max_length=30)),
                ('site_address', models.TextField()),
                ('site_status', models.IntegerField()),
                ('client_id', models.IntegerField()),
                ('site_creation_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_sites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblStatus',
            fields=[
                ('status_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(db_collation='utf8mb3_general_ci', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tbl_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblSystem',
            fields=[
                ('system_id', models.AutoField(primary_key=True, serialize=False)),
                ('system_name', models.CharField(db_collation='utf8mb3_general_ci', max_length=200)),
                ('system_ip', models.CharField(db_collation='utf8mb3_general_ci', max_length=30)),
                ('system_use', models.TextField()),
                ('system_status', models.IntegerField()),
                ('site_id', models.IntegerField()),
                ('system_creation_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_system',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblTmpclear',
            fields=[
                ('tmp_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tbl_tmpclear',
                'managed': False,
            },
        ),
    ]
